<a href="https://colab.research.google.com/github/Wiggle-Ryutsuki/MAI-KMUTT-CPE-38/blob/main/cpe232_coding_INTL_2025_ODD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CPE232: Data Models

### Portion 2: Midterm Exam Coding
---

The provided **Student_Placement_Skills_2025.csv** dataset contains structured data for 600 students, including information on:
- **Student_ID** --> Unique identifier for each student
- **Gender** --> Male and female
- **Age** --> Student age
- **Degree** --> Field of study
- **CGPA** --> Academic performance score (2.0-4.0)
- **Internships_Count** --> Number of internships completed
- **Projects_Count** --> Total academic/portfolio projects
- **Certifications_Count** --> Professional certifications earned
- **Technical_Skills_Score_100** --> Technical skill rating (0-100)
- **Communication_Skills_Score_100** --> Communication skill rating (0-100)
- **Aptitude_Test_Score_100** --> Aptitude test performance score (0–100)
- **Placement_Offer** --> Job placement offer outcome (Yes/No)
- **Salary_Offered_USD** --> Salary offered upon placement (USD)


Your task is to perform exploratory data analysis (EDA) by completing the following four subtasks.

### Subtask #1: Dataset Overview

#### 1.1) Determine structural properties (Total points = 3)

[3 points] Display the size, shape, and number of dimensions of the dataset.

In [1]:
import pandas as pd
df = pd.read_csv("Student_Placement_Skills_2025.csv")

In [15]:
# Size
print(f"Size: {df.size}")

Size: 8619

In [10]:
# Shape
print(f"Shape: {df.shape}")

Shape: (663, 13)

In [19]:
# Dimensions
print(f"Dimensions: {df.index}")

Dimensions: RangeIndex(start=0, stop=663, step=1)

#### 1.2) Data Inspection and Summary (Total points = 10)

[1 point] Display the *first 5 records* of all attributes.

In [8]:
# Write your code here
df.head(5)

,Student_ID,Gender,Age,Degree,CGPA,Internships_Count,Projects_Count,Certifications_Count,Technical_Skills_Score_100,Communication_Skills_Score_100,Aptitude_Test_Score_100,Placement_Offer,Salary_Offered_USD
0,1,Male,19,Business,2.56,3.0,8.0,0,64.0,42.0,57,Yes,8047.08
1,2,Female,27,Engineering,3.66,0.0,5.0,2,78.0,54.0,40,Yes,NaN
2,3,Male,26,Data Science,3.73,0.0,5.0,1,61.0,54.0,49,No,11791.75
3,4,Male,18,Computer Science,2.21,2.0,8.0,5,66.0,NaN,72,Yes,13946.28
4,4,Male,18,Computer Science,2.21,2.0,8.0,5,66.0,NaN,72,Yes,13946.28

[1 point] Display the *last 10 records* of all attributes.

In [9]:
# Write your code here
df.tail(10)

,Student_ID,Gender,Age,Degree,CGPA,Internships_Count,Projects_Count,Certifications_Count,Technical_Skills_Score_100,Communication_Skills_Score_100,Aptitude_Test_Score_100,Placement_Offer,Salary_Offered_USD
653,592,Female,19,Engineering,3.28,4.0,1.0,0,91.0,81.0,94,Yes,15934.35
654,593,Female,22,Arts,2.84,4.0,1.0,0,67.0,52.0,46,Yes,NaN
655,594,Female,20,Data Science,2.59,4.0,3.0,5,NaN,59.0,41,Yes,15098.55
656,595,Female,19,Business,2.78,2.0,7.0,3,80.0,53.0,64,No,NaN
657,596,Female,22,Business,2.52,3.0,9.0,4,59.0,45.0,78,No,NaN
658,597,Male,19,Data Science,2.86,NaN,9.0,1,73.0,81.0,63,Yes,8607.62
659,598,Male,28,Data Science,2.71,0.0,5.0,0,77.0,96.0,82,No,16772.72
660,599,Male,26,Engineering,2.97,3.0,4.0,3,50.0,NaN,60,No,4159.32
661,599,Male,26,Engineering,2.97,3.0,4.0,3,50.0,NaN,60,No,4159.32
662,600,Female,19,Engineering,2.13,4.0,6.0,1,69.0,NaN,90,No,11214.65

[3 points] Display the *first 3 records* of all attributes with a specific condition: `CGPA > 3.00`

In [23]:
# Write your code here
df[df["CGPA"] > 3.00].head(3)

,Student_ID,Gender,Age,Degree,CGPA,Internships_Count,Projects_Count,Certifications_Count,Technical_Skills_Score_100,Communication_Skills_Score_100,Aptitude_Test_Score_100,Placement_Offer,Salary_Offered_USD
1,2,Female,27,Engineering,3.66,0.0,5.0,2,78.0,54.0,40,Yes,NaN
2,3,Male,26,Data Science,3.73,0.0,5.0,1,61.0,54.0,49,No,11791.75
6,6,Male,21,Computer Science,3.04,2.0,4.0,0,64.0,74.0,91,No,19631.72

[1 points] Display data types of all attributes

In [21]:
# Write your code here
df.dtypes

Student_ID                          int64
Gender                             object
Age                                 int64
Degree                             object
CGPA                              float64
Internships_Count                 float64
Projects_Count                    float64
Certifications_Count                int64
Technical_Skills_Score_100        float64
Communication_Skills_Score_100    float64
Aptitude_Test_Score_100             int64
Placement_Offer                    object
Salary_Offered_USD                float64
dtype: object

[1 point] Display the descriptive statistics for *ALL attributes* in the dataset.

*Hint: The output should include statistics such as count, mean, standard deviation, minimum, maximum, and other relevant summary measures.*

In [24]:
# Write your code here
df.describe(include='all')

,Student_ID,Gender,Age,Degree,CGPA,Internships_Count,Projects_Count,Certifications_Count,Technical_Skills_Score_100,Communication_Skills_Score_100,Aptitude_Test_Score_100,Placement_Offer,Salary_Offered_USD
count,663.000000,663,663.000000,663,663.000000,535.000000,538.000000,663.000000,549.000000,537.000000,663.000000,663,520.000000
unique,NaN,2,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
top,NaN,Female,NaN,Business,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN
freq,NaN,340,NaN,140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,422,NaN
mean,299.799397,NaN,23.571644,NaN,2.976184,1.998131,5.169145,2.556561,69.353370,68.707635,69.882353,NaN,11578.782538
std,174.372965,NaN,3.440989,NaN,0.586768,1.412225,2.643853,1.697532,17.482496,17.615244,17.836316,NaN,4717.241007
min,1.000000,NaN,18.000000,NaN,2.000000,0.000000,1.000000,0.000000,40.000000,40.000000,40.000000,NaN,3127.200000
25%,150.500000,NaN,21.000000,NaN,2.460000,1.000000,3.000000,1.000000,54.000000,53.000000,54.000000,NaN,7348.690000
50%,299.000000,NaN,24.000000,NaN,2.950000,2.000000,5.000000,3.000000,70.000000,68.000000,70.000000,NaN,11723.245000
75%,450.500000,NaN,26.000000,NaN,3.505000,3.000000,8.000000,4.000000,84.000000,84.000000,86.000000,NaN,15560.462500
max,600.000000,NaN,29.000000,NaN,3.990000,4.000000,9.000000,5.000000,99.000000,99.000000,99.000000,NaN,19998.130000

[3 points] Display descriptive statistics of *four selected attributes* : `Age`, `Technical_Skills_Score_100`, `Communication_Skills_Score_100`, `Salary_Offered_USD`

In [36]:
df["Age"].describe()

count    663.000000
mean      23.571644
std        3.440989
min       18.000000
25%       21.000000
50%       24.000000
75%       26.000000
max       29.000000
Name: Age, dtype: float64

In [37]:
df["Technical_Skills_Score_100"].describe()

count    549.000000
mean      69.353370
std       17.482496
min       40.000000
25%       54.000000
50%       70.000000
75%       84.000000
max       99.000000
Name: Technical_Skills_Score_100, dtype: float64

In [38]:
df["Communication_Skills_Score_100"].describe()

count    537.000000
mean      68.707635
std       17.615244
min       40.000000
25%       53.000000
50%       68.000000
75%       84.000000
max       99.000000
Name: Communication_Skills_Score_100, dtype: float64

In [39]:
df["Salary_Offered_USD"].describe()

count      520.000000
mean     11578.782538
std       4717.241007
min       3127.200000
25%       7348.690000
50%      11723.245000
75%      15560.462500
max      19998.130000
Name: Salary_Offered_USD, dtype: float64

___

### Subtask #2: Missing and Duplicate Data Analysis

#### 2.1) Identifying Missing Values (Total points = 14)

[2 points] How many attributes contain missing values and what are they?

**ANS: There are 5 attributes with missing values**
1. Internships_Count
2. Projects_Count
3. Technical_Skills_Score
4. Communication_Skills_Score
5. Salary_Offered_USD

In [40]:
# Write your code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 663 entries, 0 to 662
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Student_ID                      663 non-null    int64
 1   Gender                          663 non-null    object
 2   Age                             663 non-null    int64
 3   Degree                          663 non-null    object
 4   CGPA                            663 non-null    float64
 5   Internships_Count               535 non-null    float64
 6   Projects_Count                  538 non-null    float64
 7   Certifications_Count            663 non-null    int64
 8   Technical_Skills_Score_100      549 non-null    float64
 9   Communication_Skills_Score_100  537 non-null    float64
 10  Aptitude_Test_Score_100         663 non-null    int64
 11  Placement_Offer                 663 non-null    object
 12  Salary_Offered_USD              520 non-null    float64
dtypes: float64(6), int64(4), object(3)
memory usage: 67.5+ KB

[2 points] For each of these attributes, how many values are missing?

**ANS:**
1. Internships_Count = 128
2. Projects_Count = 125
3. Technical_Skills_Score = 114
4. Communication_Skills_Score = 126
5. Salary_Offered_USD = 143

In [41]:
# Write your code here
df.isnull().sum()

Student_ID                          0
Gender                              0
Age                                 0
Degree                              0
CGPA                                0
Internships_Count                 128
Projects_Count                    125
Certifications_Count                0
Technical_Skills_Score_100        114
Communication_Skills_Score_100    126
Aptitude_Test_Score_100             0
Placement_Offer                     0
Salary_Offered_USD                143
dtype: int64

[5 points] What percentage of the total number of values (i.e. cells) in the dataset is missing?

**ANS:**

In [50]:
# Write your code here
df.isnull().sum()

Student_ID                          0
Gender                              0
Age                                 0
Degree                              0
CGPA                                0
Internships_Count                 128
Projects_Count                    125
Certifications_Count                0
Technical_Skills_Score_100        114
Communication_Skills_Score_100    126
Aptitude_Test_Score_100             0
Placement_Offer                     0
Salary_Offered_USD                143
dtype: int64

[5 points] Which attribute has the highest missing ratio? What is that ratio?

**ANS:**

In [ ]:
# Write your code here

#### 2.2) Identifying Duplicates (Total points = 4)

[2 points] Are there any duplicate rows in the dataset? If so, how many?

In [54]:
# Write your code here
df.duplicated().value_counts()

False    600
True      63
Name: count, dtype: int64

[2 points] Remove the duplicate rows and report the dataset shape after removal.

In [57]:
# Write your code here
df = df.drop_duplicates()
print(f"Shape: {df.shape}")

Shape: (600, 13)

From this point onward, use the above dataframe `df`, in which *duplicate rows have already been removed*.

___

### Subtask #3: Handling missing data

In [59]:
# copy dataframes
df_remove_rows = df
df_impute_zero = df

#### 3.1 Remove rows (Total points = 7)

[3 points] Using the dataframe `df_remove_rows`, remove all rows that contain missing values. Then display the dataset shape after removal.

In [63]:
# Write your code here
df_remove_rows = df_remove_rows.dropna()
df_remove_rows.shape

(202, 13)

[2 points] Compute the average `Salary_Offered_USD` after missing values have been removed.

In [75]:
# Write your code here
avg_sal = df_remove_rows["Salary_Offered_USD"].mean()
print(f"Average Salary_Offered_USD: {avg_sal}")

Average Salary_Offered_USD: 11209.62301980198

[2 points] Compute the difference between the average Salary_Offered_USD *before* and *after* missing values have been removed.

In [77]:
# Write your code here
avg_before = df["Salary_Offered_USD"].mean()

avg_after = avg_sal

print(f"Difference: {avg_before - avg_after}")

Difference: 315.2166569221572

#### 3.2 Zero Imputation (Total points = 7)

[3 points] Using the dataframe `df_impute_zero`, replace all missing values with zeros and display the first 10 rows.

In [69]:
# Write your code here
df_impute_zero = df_impute_zero.fillna(0)
df_impute_zero.head(10)

,Student_ID,Gender,Age,Degree,CGPA,Internships_Count,Projects_Count,Certifications_Count,Technical_Skills_Score_100,Communication_Skills_Score_100,Aptitude_Test_Score_100,Placement_Offer,Salary_Offered_USD
0,1,Male,19,Business,2.56,3.0,8.0,0,64.0,42.0,57,Yes,8047.08
1,2,Female,27,Engineering,3.66,0.0,5.0,2,78.0,54.0,40,Yes,0.00
2,3,Male,26,Data Science,3.73,0.0,5.0,1,61.0,54.0,49,No,11791.75
3,4,Male,18,Computer Science,2.21,2.0,8.0,5,66.0,0.0,72,Yes,13946.28
5,5,Male,20,Business,2.59,3.0,9.0,2,69.0,0.0,53,No,0.00
6,6,Male,21,Computer Science,3.04,2.0,4.0,0,64.0,74.0,91,No,19631.72
7,7,Male,25,Data Science,2.42,0.0,8.0,4,50.0,61.0,65,Yes,0.00
8,8,Female,28,Data Science,2.48,4.0,8.0,2,0.0,57.0,50,No,13036.97
9,9,Female,27,Engineering,3.02,0.0,3.0,4,49.0,0.0,76,Yes,16192.47
10,10,Male,29,Data Science,3.01,2.0,4.0,2,0.0,90.0,67,No,12022.49

[2 points] Compute the average `Technical_Skills_Score_100` after imputation.

In [78]:
# Write your code here
avg_tech = df_impute_zero["Technical_Skills_Score_100"].mean()
print(f"Average_Technical_Skills_Score_100: {avg_tech}")

Average_Technical_Skills_Score_100: 56.968333333333334

[2 points] Compute the difference between the average `Technical_Skills_Score_100` *before* and *after* replacing missing values with zeros.

In [79]:
# Write your code here
avg_tech_before = df["Technical_Skills_Score_100"].mean()
avg_tech_after = avg_tech

print(f"Difference: {avg_tech_before - avg_tech_after}")

Difference: 12.084191919191923

#### 3.3 Mean Imputation (Total points = 15)

[3 points] Create a new dataframe `df_new` which contains only the following attributes from the original dataframe `df`:
- `Age`
- `Degree`
- `CGPA`
- `Projects_Count`
- `Technical_Skills_Score_100`
- `Communication_Skills_Score_100`
- `Aptitude_Test_Score_100`.

Then, display the first 10 rows.

In [86]:
# Write your code here
df_new = pd.DataFrame(df['Age', 'Degree', 'CGPA', 'Projects_Count', 'Technical_Skills_Score_100', 'Communication_Skills_Score_100', 'Aptitude_Test_Score_100'])
df_new.head(10)

InvalidIndexError: (['Age'], ['Degree'], ['CGPA'], ['Projects_Count'], ['Technical_Skills_Score_100'], ['Communication_Skills_Score_100'], ['Aptitude_Test_Score_100'])

We are going to replace missing values in the attribute `Technical_Skills_Score_100` with its average.

[2 points] Compute the average of `Technical_Skills_Score_100` using the new dataframe `df_new`.

In [ ]:
# Write your code here

[3 points] Replace any missing values in `Technical_Skills_Score_100` in `df_new` with the computed average. Then display the first 10 rows.

In [ ]:
# Write your code here

[7 points] Discuss which missing data handling method (row removal, zero imputation, or mean imputation) is most appropriate in this case and justify your answer.


**ANS:**

___

### Subtask #4: Visualizations and Analysis

In [87]:
import matplotlib.pyplot as plt

In [ ]:
import numpy as np

##### 4.1 Investigate impact of internship (Total points = 12)

[5 points] Using the dataframe `df_remove_rows`, create a bar chart showing the average salary for each internship count.

The x-axis should represent the number of internships, and the y-axis should represent the average salary.

Include an appropriate plot title and axis labels.

In [113]:
# Get each internship count
x_axis = df_remove_rows["Internships_Count"].value_counts()
print({x_axis})
# Calculate average of each internship count

y_axis = df_remove_rows["Salary_Offered_USD"].mean()
"""plt.bar(x_axis, y_axis)
plt.title("Average Salary per Internship Count")
plt.xlabel("Number of Internships")
plt.ylabel("Average Salary")
plt.show()"""

TypeError: unhashable type: 'Series'

[7 points] Interpret the visualization above. What insights can you draw from it? Provide a reasoned explanation and discuss any potential limitations of your interpretation.

**ANS**

##### 4.2 Investigate proportion of students in different degrees via pie charts (Total points = 12)

[5 points] Using the dataframe `df_remove_rows`, create two pie charts showing the distribution of students across degree categories: one for male students and one for female students.

Include appropriate chart titles and percentage labels.

In [111]:
# Write your code here

[7 points] Interpret the visualizations above. What insights can you draw from them? Provide a reasoned explanation and discuss any potential limitations of your interpretation.

**ANS:**

##### 4.3 Investigate proportion of students in different degrees via a bar chart  (Total points = 16)

[5 points] Using the dataframe `df_remove_rows`, create a side-by-side bar chart to compare the proportion of male and female students across degree categories.

The x-axis should represent degree categories, and the y-axis should represent the proportion of students.

Include appropriate chart titles, axis labels, and a legend.

In [ ]:
# Write your code here

[7 points] Interpret the visualization above. What insights can you draw from it? Provide a reasoned explanation and discuss any potential limitations of your interpretation.

**ANS:**

[4 points] Compare the pie charts in Section 4.2 with the bar chart in Section 4.3. Which visualization is more effective for comparing degree distributions by gender? Justify your answer.

**ANS:**

___